# Generated by Django 4.2.16 on 2024-09-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_parts_options_category_level_category_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catCode',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
