# Generated by Django 4.2.16 on 2024-09-26 08:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_category_catcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование материала')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Код материала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость материала')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='catCode',
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='Код категории'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.category', verbose_name='Родительский элемент'),
        ),
        migrations.DeleteModel(
            name='Parts',
        ),
        migrations.AddField(
            model_name='materials',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.category', verbose_name='Категория'),
        ),
    ]
