# Generated by Django 4.2.16 on 2024-09-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_materials_remove_category_catcode_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='code',
            field=models.PositiveIntegerField(verbose_name='Код материала'),
        ),
    ]
