# Generated by Django 4.2.16 on 2024-09-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_materials_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Код материала'),
        ),
    ]
