# Generated by Django 4.2.16 on 2024-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_profile_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование материала')),
                ('code', models.PositiveIntegerField(unique=True, verbose_name='Код материала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость материала')),
            ],
        ),
    ]
