# Generated by Django 4.2.16 on 2024-10-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_materialtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
