# Generated by Django 4.2.16 on 2024-10-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_categorytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTest',
        ),
    ]
