# Generated by Django 4.2.16 on 2024-10-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_categorytest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytest',
            old_name='code',
            new_name='codeCat',
        ),
        migrations.RenameField(
            model_name='categorytest',
            old_name='name',
            new_name='nameCat',
        ),
    ]
