# Generated by Django 4.2.16 on 2024-10-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_code_categorytest_codecat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorytest',
            old_name='codeCat',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='categorytest',
            old_name='nameCat',
            new_name='name',
        ),
    ]
