# Generated by Django 4.2.16 on 2024-10-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_codecat_categorytest_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTest',
        ),
        migrations.DeleteModel(
            name='MaterialTest',
        ),
    ]
