# Generated by Django 4.2.16 on 2024-10-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_categorytest_materialtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytest',
            name='parent',
            field=models.CharField(default='null', max_length=100, verbose_name='Родительский элемент'),
        ),
    ]
