# Generated by Django 4.2.16 on 2024-10-17 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_categorytest_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryTest',
        ),
        migrations.DeleteModel(
            name='MaterialTest',
        ),
    ]
